repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        name: trailing-whitespace (check only)
        description: |
          Found trailing whitespace. Run this to fix:
          git diff --name-only | xargs sed -i '' 's/[[:space:]]*$//'
    -   id: end-of-file-fixer
        name: end-of-file-fixer (check only)
        description: |
          Files should end with a newline. Run this to fix:
          git diff --name-only | xargs sed -i '' -e '$a\'
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        args: [--check]
        name: black (check only)
        description: |
          Black would reformat your code. Run this to fix:
          black .

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        args: ["--check-only", "--profile", "black"]
        name: isort (check only)
        description: |
          isort would sort your imports. Run this to fix:
          isort .

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.10
    hooks:
    -   id: ruff
        args: [--exit-non-zero-on-fix]
        name: ruff (check only)
        description: |
          Ruff found issues. Run this to fix:
          ruff check --fix .
