site_name: AI Refactor Bot Documentation
site_description: Documentation for the AI Refactoring Bot project
site_author: AI Refactoring Bot Team
repo_url: https://github.com/yourusername/ai-refactor-bot
repo_name: ai-refactor-bot

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - pymdownx.emoji:
      emoji_index: materialx.emoji.twemoji
      emoji_generator: materialx.emoji.to_svg
  - admonition
  - footnotes
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
  - User Guide:
    - Features: user-guide/features.md
  - API:
    - Overview: api/overview.md
    - Endpoints: api/endpoints.md
  - Development:
    - Architecture: development/architecture.md
    - Guide: development.md
  - Deployment: deployment.md
  - Troubleshooting: troubleshooting.md
  - Templates:
    - API Endpoint: templates/api-endpoint.md
    - Feature: templates/feature.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true

exclude:
  - venv/
