site_name: AI Refactoring Bot
site_description: Documentation for the AI Refactoring Bot project
site_author: AI Refactoring Bot Team
repo_url: https://github.com/yourusername/ai-refactor-bot
repo_name: ai-refactor-bot

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - pymdownx.emoji:
      emoji_index: materialx.emoji.twemoji
      emoji_generator: materialx.emoji.to_svg
  - admonition
  - footnotes
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Features: user-guide/features.md
    - Usage: user-guide/usage.md
    - Best Practices: user-guide/best-practices.md
  - Development:
    - Setup: development/setup.md
    - Architecture: development/architecture.md
    - Contributing: development/contributing.md
    - Testing: development/testing.md
  - API Reference:
    - Overview: api/overview.md
    - Endpoints: api/endpoints.md
    - Authentication: api/authentication.md
  - Deployment:
    - Overview: deployment/overview.md
    - Railway: deployment/railway.md
    - Docker: deployment/docker.md
    - Manual: deployment/manual.md
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - Debugging: troubleshooting/debugging.md
    - FAQ: troubleshooting/faq.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
